-- Seed: employment-law obligations, written from primary sources (2026-09-02).
--
-- Every row was written from the government text quoted in source_quote and
-- linked in official_url. Rows we could not verify against the primary source in
-- this pass are marked review_status = 'needs_review' rather than asserted.
--
-- Applied to prod as `seed_law_obligations`.

insert into public.law_obligations (
  org_id, title, jurisdiction, topic, authority_body, citation_label, official_url,
  applies_all, min_employees, count_basis, conditions, summary, employer_duties,
  deadline_note, penalty_note, source_quote, verified_at, review_status
)
select o.id, v.* from public.organizations o cross join (values

-- ---------------------------------------------------------------- federal --
($q$Title VII — discrimination, harassment and retaliation$q$, 'federal', 'discrimination', 'EEOC',
 '42 U.S.C. 2000e(b); enforced by EEOC', 'https://www.eeoc.gov/employers/coverage-businessprivate-employers',
 false, 15, '15 or more employees for at least 20 calendar weeks in the current or preceding year', '{}'::text[],
 $q$Bars employment discrimination on race, color, religion, sex (including pregnancy, sexual orientation and gender identity) and national origin, and retaliation for protected activity.$q$,
 array['Maintain and distribute an anti-harassment and non-retaliation policy','Investigate complaints and document the outcome','Display the EEO poster','Preserve personnel records tied to any charge'],
 null, null,
 $q$15 or more employees who worked for the employer for at least twenty calendar weeks$q$,
 now(), 'verified'),

($q$ADA Title I — disability discrimination and accommodation$q$, 'federal', 'discrimination', 'EEOC',
 '42 U.S.C. 12111(5); enforced by EEOC', 'https://www.eeoc.gov/employers/coverage-businessprivate-employers',
 false, 15, '15 or more employees for at least 20 calendar weeks in the current or preceding year', '{}'::text[],
 $q$Requires reasonable accommodation for qualified individuals with disabilities absent undue hardship, and limits medical inquiries and exams.$q$,
 array['Run an interactive accommodation process and document each request','Keep medical information in a file separate from the personnel file','Confine pre-offer questions to ability to perform the job'],
 null, null,
 $q$15 or more employees who worked for the employer for at least twenty calendar weeks$q$,
 now(), 'verified'),

($q$GINA — genetic information$q$, 'federal', 'discrimination', 'EEOC',
 '42 U.S.C. 2000ff; enforced by EEOC', 'https://www.eeoc.gov/employers/coverage-businessprivate-employers',
 false, 15, '15 or more employees for at least 20 calendar weeks in the current or preceding year', '{}'::text[],
 $q$Bars use of genetic information (including family medical history) in employment decisions and restricts its acquisition.$q$,
 array['Include GINA safe-harbor language on any medical certification request','Keep any genetic information confidential and segregated'],
 null, null,
 $q$15 or more employees who worked for the employer for at least twenty calendar weeks$q$,
 now(), 'verified'),

($q$ADEA — age discrimination (40+)$q$, 'federal', 'discrimination', 'EEOC',
 '29 U.S.C. 630(b); enforced by EEOC', 'https://www.eeoc.gov/employers/coverage-businessprivate-employers',
 false, 20, '20 or more employees for at least 20 calendar weeks in the current or preceding year', '{}'::text[],
 $q$Bars discrimination against workers aged 40 and over in any employment decision, including hiring, pay and termination.$q$,
 array['Keep age out of job ads and screening criteria','Use the OWBPA waiver form and 21/45-day consideration periods for any separation release'],
 null, null,
 $q$20 or more employees who worked for the company for at least twenty calendar weeks$q$,
 now(), 'verified'),

($q$Equal Pay Act — equal pay for substantially equal work$q$, 'federal', 'wage_hour', 'EEOC',
 '29 U.S.C. 206(d); enforced by EEOC', 'https://www.eeoc.gov/employers/coverage-businessprivate-employers',
 true, null, 'Virtually all employers', '{}'::text[],
 $q$Prohibits paying different wages to men and women performing substantially equal work in the same establishment.$q$,
 array['Document the factor other than sex behind any pay differential between comparable roles'],
 null, null,
 $q$Virtually all employers are covered by the Equal Pay Act (EPA)$q$,
 now(), 'verified'),

($q$Pregnant Workers Fairness Act — accommodation for pregnancy and related conditions$q$, 'federal', 'leave', 'EEOC',
 '42 U.S.C. 2000gg; enforced by EEOC', 'https://www.eeoc.gov/wysk/what-you-should-know-about-pregnant-workers-fairness-act',
 false, 15, 'Uses the Title VII employer definition — 15 or more employees', '{}'::text[],
 $q$Requires reasonable accommodation for known limitations related to pregnancy, childbirth or related medical conditions absent undue hardship.$q$,
 array['Accept and document accommodation requests without requiring medical certification by default','Do not force leave when another accommodation would work'],
 null, null,
 null, null, 'needs_review'),

($q$COBRA — group health continuation coverage$q$, 'federal', 'benefits', 'DOL / EBSA',
 '26 U.S.C. 4980B; ERISA 601 et seq.', 'https://www.dol.gov/agencies/ebsa/about-ebsa/our-activities/resource-center/publications/an-employers-guide-to-group-health-continuation-coverage-under-cobra',
 false, 20, '20 or more employees on more than 50% of typical business days in the previous calendar year; part-timers count fractionally', '{group_health_plan}'::text[],
 $q$A group health plan sponsored by an employer at or above the 20-employee line must offer continuation coverage to qualified beneficiaries after a qualifying event.$q$,
 array['Send the general (initial) notice within 90 days of coverage starting','Notify the plan within 30 days of a termination, hours reduction, death or Medicare entitlement','Have the plan send the election notice within 14 days','Allow at least 60 days to elect'],
 'General notice: 90 days. Employer-to-plan notice: 30 days. Election notice: 14 days. Election period: 60 days.',
 null,
 $q$employers with at least 20 employees on more than 50 percent of their typical business days in the previous calendar year$q$,
 now(), 'verified'),

($q$FMLA — job-protected family and medical leave$q$, 'federal', 'leave', 'DOL / WHD',
 '29 U.S.C. 2611; 29 CFR 825', 'https://www.dol.gov/agencies/whd/fact-sheets/28-fmla',
 false, 50, '50 or more employees in 20 or more workweeks in the current or previous calendar year', '{}'::text[],
 $q$Covered employers must provide eligible employees up to 12 workweeks of unpaid, job-protected leave for their own or a family member serious health condition, birth or placement, and qualifying military reasons.$q$,
 array['Post the FMLA general notice and include it in the handbook','Issue eligibility, rights-and-responsibilities and designation notices','Maintain group health coverage during leave','Restore the employee to the same or an equivalent job'],
 'Employee eligibility also requires 12 months of service, 1,250 hours, and a worksite with 50 employees within 75 miles.',
 null,
 $q$employ 50 or more employees in 20 or more workweeks in either the current calendar year or previous calendar year$q$,
 now(), 'verified'),

($q$ACA employer mandate and 1094-C/1095-C reporting$q$, 'federal', 'benefits', 'IRS',
 '26 U.S.C. 4980H; 6055/6056', 'https://www.irs.gov/affordable-care-act/employers/determining-if-an-employer-is-an-applicable-large-employer',
 false, 50, 'Average of 50 or more full-time plus full-time-equivalent employees during the prior calendar year (full time = 30 hours/week)', '{}'::text[],
 $q$An applicable large employer must offer affordable minimum-value coverage to full-time employees and file annual information returns, or face shared-responsibility payments.$q$,
 array['Run the ALE calculation each year and keep the working','Track full-time status by month','File Forms 1094-C and 1095-C and furnish 1095-C to employees'],
 null, null,
 $q$If an employer has at least 50 full-time employees, including full-time equivalent employees, on average during the prior year, the employer is an ALE for the current calendar year.$q$,
 now(), 'verified'),

($q$EEO-1 Component 1 report$q$, 'federal', 'recordkeeping', 'EEOC',
 '29 CFR 1602.7', 'https://www.eeoc.gov/employers/small-business/legal-requirements',
 false, 100, '100 or more employees (50 or more for federal contractors)', '{}'::text[],
 $q$Private employers at or above the threshold file an annual demographic workforce report with the EEOC.$q$,
 array['File the annual EEO-1 Component 1 report during the collection window'],
 'Watch item: on 23 July 2026 the EEOC published a proposed rule that would eliminate EEO-1 reporting. It is a proposal only — nothing has changed yet.',
 null,
 $q$Employers who have at least 100 employees and federal contractors who have at least 50 employees are required to complete and submit an EEO-1 Report$q$,
 now(), 'verified'),

($q$OSHA injury and illness recordkeeping (300 / 300A / 301)$q$, 'federal', 'safety', 'OSHA',
 '29 CFR 1904.1, 1904.2 and App. A to Subpart B', 'https://www.osha.gov/laws-regs/regulations/standardnumber/1904/1904SubpartBAppA',
 false, 11, 'More than 10 employees at any time in the prior calendar year — AND the establishment NAICS is not on the partial-exemption list', '{osha_partially_exempt_naics}'::text[],
 $q$Establishments classified in NAICS 6211 (offices of physicians), 6213 (offices of other health practitioners) and 6214 (outpatient care centers) are on OSHA partial-exemption list, which removes the routine 300/300A/301 recordkeeping duty even above 10 employees. Confirm the establishment NAICS before relying on this — and note the exemption does not touch severe-injury reporting, the bloodborne pathogens standard, hazard communication, or a written request from OSHA or BLS.$q$,
 array['Confirm and document the establishment NAICS code','If not exempt: maintain the 300 log, post the 300A from 1 February to 30 April, and keep 301 forms for five years','Respond to any written OSHA or BLS survey request regardless of exemption'],
 null, null,
 $q$Employers are not required to keep OSHA injury and illness records for any establishment classified in the following...NAICS codes, unless they are asked in writing to do so by OSHA, the Bureau of Labor Statistics (BLS), or a state agency$q$,
 now(), 'verified'),

($q$OSHA severe-injury reporting$q$, 'federal', 'safety', 'OSHA',
 '29 CFR 1904.39', 'https://www.ecfr.gov/current/title-29/subtitle-B/chapter-XVII/part-1904/subpart-E/section-1904.39',
 true, null, 'Every employer, including establishments partially exempt from routine recordkeeping', '{}'::text[],
 $q$Work-related deaths and severe injuries must be reported to OSHA directly, on a clock measured in hours.$q$,
 array['Report a work-related fatality within 8 hours','Report an in-patient hospitalization, amputation or loss of an eye within 24 hours','Report by phone to the area office, the 800 number, or the OSHA web form — voicemail, fax and email are not acceptable'],
 'Fatality: within 8 hours, if death occurs within 30 days of the incident. Hospitalization/amputation/eye loss: within 24 hours, if it occurs within 24 hours of the incident.',
 null,
 $q$Within eight (8) hours after the death of any employee as a result of a work-related incident, you must report the fatality to the Occupational Safety and Health Administration (OSHA)$q$,
 now(), 'verified'),

($q$FLSA — minimum wage, overtime and time records$q$, 'federal', 'wage_hour', 'DOL / WHD',
 '29 U.S.C. 201 et seq.', 'https://www.dol.gov/agencies/whd/flsa',
 true, null, 'Enterprise coverage at $500,000 in annual volume, or individual coverage', '{}'::text[],
 $q$Sets the federal minimum wage and time-and-a-half overtime above 40 hours in a workweek for non-exempt employees, and requires payroll records.$q$,
 array['Classify each role exempt/non-exempt and keep the analysis','Keep time records for non-exempt staff for three years','Keep the records supporting wage computations for two years'],
 null, null, null, null, 'needs_review'),

($q$PUMP Act — break time and space for nursing employees$q$, 'federal', 'leave', 'DOL / WHD',
 '29 U.S.C. 218d', 'https://www.dol.gov/agencies/whd/pump-at-work',
 true, null, 'All FLSA-covered employers; employers with fewer than 50 employees may claim undue hardship', '{}'::text[],
 $q$Requires reasonable break time and a private, non-bathroom space for an employee to express breast milk.$q$,
 array['Designate a private space that is not a bathroom and is shielded from view','Allow break time as needed for up to one year after birth'],
 null, null, null, null, 'needs_review'),

($q$Form I-9 employment eligibility verification$q$, 'federal', 'hiring', 'USCIS / DHS',
 '8 U.S.C. 1324a; 8 CFR 274a', 'https://www.uscis.gov/i-9',
 true, null, 'Every employer, for every employee hired', '{}'::text[],
 $q$Every new hire must complete Form I-9 and the employer must examine acceptable documents within the statutory window.$q$,
 array['Section 1 by the first day of work; employer review within 3 business days','Store I-9s separately from personnel files','Purge on the later of 3 years from hire or 1 year from separation'],
 null, null, null, null, 'needs_review'),

($q$USERRA — military service leave and reinstatement$q$, 'federal', 'leave', 'DOL / VETS',
 '38 U.S.C. 4301 et seq.', 'https://www.dol.gov/agencies/vets/programs/userra',
 true, null, 'All employers, regardless of size', '{}'::text[],
 $q$Protects the job, seniority and benefits of employees who leave for uniformed service.$q$,
 array['Post the USERRA rights notice','Reinstate on the escalator principle after qualifying service'],
 null, null, null, null, 'needs_review'),

($q$Federal new hire reporting$q$, 'federal', 'hiring', 'HHS / OCSE',
 '42 U.S.C. 653a', 'https://www.acf.hhs.gov/css/employers',
 true, null, 'Every employer required to issue a W-2', '{}'::text[],
 $q$Newly hired and rehired employees must be reported to the state directory of new hires.$q$,
 array['Report each new or rehired employee to the Utah New Hire Registry within 20 days'],
 null, null, null, null, 'needs_review'),

-- ------------------------------------------------------------------ Utah --
($q$Utah Antidiscrimination Act$q$, 'UT', 'discrimination', 'Utah Labor Commission',
 'Utah Code 34A-5-102(1)(i)(D)', 'https://le.utah.gov/xcode/Title34a/Chapter5/34a-5-S102.html',
 false, 15, '15 or more employees within the state for each working day in each of 20 calendar weeks or more in the current or preceding calendar year', '{}'::text[],
 $q$Utah state-law counterpart to Title VII, enforced by the Labor Commission Antidiscrimination and Labor Division, with its own charge process and deadlines.$q$,
 array['Handle state charges through UALD as well as EEOC','Apply Utah protected classes alongside federal ones'],
 null, null,
 $q$a person employing 15 or more employees within the state for each working day in each of 20 calendar weeks or more in the current or preceding calendar year$q$,
 now(), 'verified'),

($q$Utah pregnancy, childbirth and breastfeeding accommodation$q$, 'UT', 'leave', 'Utah Labor Commission',
 'Utah Code 34A-5-106(1)(g)', 'https://le.utah.gov/xcode/Title34A/Chapter5/34A-5-S106.html',
 false, 15, 'Uses the Utah Antidiscrimination Act employer definition — 15 or more employees', '{}'::text[],
 $q$An employer may not refuse reasonable accommodations related to pregnancy, childbirth, breastfeeding or related conditions when requested, absent undue hardship, and may not force termination or leave where another accommodation exists.$q$,
 array['Document each request and the accommodation provided','Do not require leave where another accommodation would work'],
 null, null,
 $q$refuse to provide reasonable accommodations for an employee related to pregnancy, childbirth, breastfeeding, or related conditions$q$,
 now(), 'verified'),

($q$Utah Payment of Wages — pay frequency$q$, 'UT', 'wage_hour', 'Utah Labor Commission',
 'Utah Code 34-28-3', 'https://le.utah.gov/xcode/Title34/Chapter28/34-28-S3.html',
 true, null, 'All employers with employees in Utah', '{}'::text[],
 $q$Wages must be paid at regular intervals no longer than semimonthly, and within 10 days of the close of the pay period.$q$,
 array['Pay at least semimonthly','Pay within 10 days after each pay period closes'],
 null, null,
 $q$An employer shall pay the wages earned by an employee at regular intervals, but in periods no longer than semimonthly ... within 10 days after the close of that pay period$q$,
 now(), 'verified'),

($q$Utah final wages on separation$q$, 'UT', 'termination', 'Utah Labor Commission',
 'Utah Code 34-28-5', 'https://le.utah.gov/xcode/Title34/Chapter28/34-28-S5.html',
 true, null, 'All employers with employees in Utah', '{}'::text[],
 $q$On discharge, unpaid wages are due immediately and must be paid within 24 hours of separation. An employee who resigns is paid on the next regular payday. Missing the 24-hour deadline carries a continuing-wage penalty.$q$,
 array['Pay a discharged employee within 24 hours of separation','Pay a resigning employee on the next regular payday','Build the 24-hour payment into the termination checklist'],
 'Discharge: 24 hours. Resignation: next regular payday.',
 $q$Wages continue from the date of written demand until paid, up to 60 days, at the employee separation rate.$q$,
 $q$the unpaid wages of the employee become due immediately, and the employer shall pay the wages to the employee within 24 hours of the time of separation$q$,
 now(), 'verified'),

($q$Utah new hire reporting$q$, 'UT', 'hiring', 'Utah Department of Workforce Services',
 'Utah New Hire Registry', 'https://jobs.utah.gov/ui/employer/public/NewHire/NewHireHandbook.aspx',
 true, null, 'Every employer required to issue W-2s', '{}'::text[],
 $q$Newly hired and rehired employees must be reported to the Utah New Hire Registry.$q$,
 array['Report name, SSN, date of hire and employer FEIN within 20 days of the first day of work'],
 'Within 20 days of the first day of work.',
 null,
 $q$Every employer is required to report all newly hired or rehired employees within 20 days of their first day of work.$q$,
 now(), 'verified'),

($q$Utah workers compensation coverage$q$, 'UT', 'safety', 'Utah Labor Commission',
 'Utah Code 34A-2-201 et seq.', 'https://laborcommission.utah.gov/divisions/industrial-accidents/employers/employers-guide-to-workers-compensation/',
 true, null, 'With few exceptions, every employer with employees', '{}'::text[],
 $q$Employers must carry workers compensation coverage, post the compliance notice, and report injuries to the carrier on Form 122e.$q$,
 array['Maintain coverage and keep the certificate on file','Post the workers compensation notice conspicuously','File Form 122e with the carrier within 7 days of a reported injury and give the worker a copy'],
 'Employer to carrier: 7 days. Carrier to the Industrial Accidents Division: 14 days.',
 null,
 $q$With a few exceptions, every employer is required to provide workers compensation coverage for all its employees.$q$,
 now(), 'verified'),

($q$Utah minimum wage$q$, 'UT', 'wage_hour', 'Utah Labor Commission',
 'Utah Code 34-40-103', 'https://le.utah.gov/xcode/Title34/Chapter40/34-40-S103.html',
 true, null, 'All employers subject to the Utah Minimum Wage Act', '{}'::text[],
 $q$Utah minimum wage tracks the federal rate. Confirm the current figure against the statute before relying on it.$q$,
 array['Pay at or above the federal/state minimum','Post the Utah minimum wage notice'],
 null, null, null, null, 'needs_review'),

($q$HIPAA Privacy and Security Rules (as a covered entity)$q$, 'federal', 'privacy', 'HHS / OCR',
 '45 CFR Parts 160 and 164', 'https://www.hhs.gov/hipaa/for-professionals/index.html',
 true, null, 'Applies as a health care provider transmitting electronic standard transactions', '{covered_entity}'::text[],
 $q$Clinic-side HIPAA obligations, distinct from the group-health-plan HIPAA duties an HR platform covers. The Hub security risk assessment, breach assessment and BAA tracking discharge parts of this.$q$,
 array['Keep the security risk analysis current','Run the four-factor breach risk assessment on each incident','Hold a BAA with every vendor that touches PHI','Train the workforce and document it'],
 null, null, null, null, 'needs_review')

) as v(title, jurisdiction, topic, authority_body, citation_label, official_url,
       applies_all, min_employees, count_basis, conditions, summary, employer_duties,
       deadline_note, penalty_note, source_quote, verified_at, review_status)
where not exists (
  select 1 from public.law_obligations x where x.org_id = o.id and x.title = v.title
);
